type Query {
  staffs(pagination: Pagination = {}, search: String): [Staff!]!
  staff(staffId: ID!): Staff
}

type Mutation {
  login(staffname: String!, staffPassword: String!): AuthResponse!
  mutation
}

type Staff {
  staffId: ID!
  staffname: String!
  staffBirthDate: String!
  staffWorkPlace: String!
  fullAdress: String!
  staffCreatedAt: String!
}
