type Query {
  staffs(pagination: Pagination = {}, search: String): [Staff!]!
  staff(staffId: ID!): Staff
}

type Mutation {
  login(staffname: String!, staffPassword: String!): AuthResponse!
  register(
    staffname: String!
    staffPassword: String!
    confirmPassword: String!
    staffBirthDate: String!
    brancheId: ID!
  ): AuthResponse!
}

type Staff {
  staffId: ID!
  staffname: String!
  staffBirthDate: String!
  staffWorkPlace: String!
  fullAdress: String!
  staffCreatedAt: String!
}
