scalar Link

## pagination input

input Pagination {
  page: Int
  limit: Int
}

## enum types

enum SortOptions {
  toLargest
  toSmallest
}

type MutationResponse {
  status: Int!
  message: String!
  data: GlobalType
}

type AuthResponse {
  status: Int!
  message: String!
  token: String
  data: GlobalType
}

union GlobalType = Staff | Branch | Transport
